# Generated by Django 3.1.5 on 2021-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterVirualCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationId', models.CharField(max_length=100)),
                ('tranDateTime', models.DateTimeField()),
                ('UUID', models.CharField(max_length=36, verbose_name='UUID')),
                ('expDate', models.CharField(max_length=5, null=True)),
                ('IPIN', models.CharField(max_length=250, null=True)),
                ('PAN', models.CharField(max_length=19, null=True)),
                ('mbr', models.CharField(max_length=3, null=True)),
                ('responseMessage', models.CharField(max_length=100, null=True)),
                ('responseCode', models.PositiveSmallIntegerField(null=True)),
                ('responseStatus', models.CharField(max_length=100, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=40, null=True)),
                ('phoneNo', models.CharField(max_length=12, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('entityType', models.CharField(choices=[('Phone No', 'Phone NO'), ('Meter No', 'Meter No'), ('Credit Card', 'Credit Card'), ('Cash Card', 'Credit Card'), ('Mobile Wallet', 'Mobile Wallet')], default='Phone No', max_length=20, verbose_name='entityID type')),
                ('entityId', models.CharField(max_length=30, null=True)),
                ('entityGroup', models.CharField(max_length=1, null=True)),
                ('panCategory', models.CharField(choices=[('Standard', 'Standard'), ('Silver', 'Silver'), ('Golden', 'Golden'), ('Silver Agent', 'Silver Agent'), ('Golden Agent', 'Golden Agent')], default='Standard', max_length=12, null=True)),
                ('financialInstitutionId', models.CharField(max_length=4)),
                ('fullName', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('customerIdType', models.CharField(choices=[('National ID', 'National ID'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], default='National ID', max_length=36, null=True)),
                ('customerIdNumber', models.CharField(max_length=40)),
                ('bankAccountNumber', models.CharField(max_length=36)),
                ('bankAccountType', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings'), ('Credit', 'Credit'), ('Bonus', 'Bonus')], default='Checking', max_length=36, null=True)),
                ('bankBranchId', models.CharField(max_length=3)),
                ('bankId', models.CharField(max_length=3)),
                ('job', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address')),
            ],
        ),
    ]
