# Generated by Django 3.1.5 on 2021-03-30 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_pan', models.TextField()),
                ('card_expiry', models.TextField()),
                ('card_user', models.IntegerField(default=0)),
                ('card_added', models.DateTimeField(default=datetime.datetime.now)),
                ('card_label', models.TextField(default='Null')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
