# Generated by Django 3.1.5 on 2021-03-22 10:26

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_mobile_number', models.CharField(default=None, max_length=20, validators=[accounts.validators.CardHolderMobileNumberValidator()], verbose_name='mobile number')),
                ('private_key', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
