# Generated by Django 3.1.5 on 2021-03-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIKEY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedtoken',
            name='token',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
