# Generated by Django 3.1.5 on 2021-03-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jwt_secret_key',
            new_name='otp',
        ),
        migrations.AlterField(
            model_name='user',
            name='card_holder_id_type',
            field=models.IntegerField(blank=True, choices=[(0, 'National ID'), (1, 'Passport Number'), (3, 'Driving License')], null=True, verbose_name='entityID type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Card Holder')], default=1),
        ),
    ]
