# Generated by Django 3.1.5 on 2021-03-25 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210322_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
    ]
