# Generated by Django 3.1.5 on 2021-03-27 12:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210327_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_holder_mobile_number',
            field=models.CharField(default=0, max_length=20, unique=True, validators=[accounts.validators.CardHolderMobileNumberValidator()], verbose_name='mobile number'),
            preserve_default=False,
        ),
    ]
