# Generated by Django 3.1.5 on 2022-05-29 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, default=datetime.date.today, max_length=3, null=True),
        ),
    ]
