# Generated by Django 3.1.5 on 2023-02-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebs_consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('END_POINT', models.CharField(default='https://172.16.199.1:8877/QAConsumer', max_length=500, null=True)),
                ('APPLICATION_ID', models.CharField(default='CashMash', max_length=100)),
                ('VERIFY_SSL', models.BooleanField(default=False)),
                ('TIMEOUT', models.IntegerField(default=60)),
                ('TIME_ZONE', models.CharField(default='Africa/Khartoum', max_length=100)),
            ],
        ),
    ]
