# Generated by Django 3.1.5 on 2023-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBS_CONSUMER_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebs_consumer',
            name='APPLICATION_ID',
            field=models.CharField(default='ITQAN', max_length=100),
        ),
    ]
