# Generated by Django 3.1.5 on 2023-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EBS_CONSUMER_API', '0002_auto_20230313_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPublickey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('expired', models.DateField()),
                ('pubKeyValue', models.TextField(verbose_name='')),
                ('responseCode', models.IntegerField()),
                ('responseMessage', models.CharField(max_length=50)),
                ('responseStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
